export const ORGANIZATIONS_GET = 'ORGANIZATIONS_GET'
export const ORGANIZATIONS_GET_SUCCESS = 'ORGANIZATIONS_GET_SUCCESS'
export const ORGANIZATIONS_GET_ERROR = 'ORGANIZATIONS_GET_ERROR'
export const ORGANIZATION_TOGGLE_ACTIVATED = 'ORGANIZATION_TOGGLE_ACTIVATED'

